import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { AppBar, Button, IconButton, Toolbar, Typography } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AppBar>
            <Toolbar sx={{ justifyContent: 'space-between' }}>
                <IconButton
                size="large"
                edge="start"
                color="inherit"
                aria-label="menu"
                sx={{ mr: 2 }}
                >
                    Hashtable
                </IconButton>
                <Button color="inherit">Login</Button>
            </Toolbar>
        </AppBar>
      </main>
    </>
  )
}
