import Head from "next/head";
import Navbar from "@/components/Navbar";
import Cards from "@/components/Cards";
import { Hero } from "@/components/Hero";
import Search from "@/components/Search";
import Footer from "@/components/Footer";
import { getSectionIndex, getSections, Section } from "lib/sections";

export async function getStaticProps() {
    const sections = await getSections();

    const data: Section[] = await Promise.all(
        sections.map(async (section: string) => {
            const sectionData: Section = await getSectionIndex(section)
            return { section, ...sectionData }
        })
    )

    return {
        props: {
            data
        },
    };
}

export default function Home({ data }: { data: Section[] }) {
    return (
        <>
            <Head>
                <title>Hashtable</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                <Hero>
                    <h4 className="text-xl md:text-2xl lg:text-3xl 2xl:text-4xl">Stuck in a Problem?</h4>
                    <Search />
                </Hero>
             
                <section className="xl:max-w-[120ch] mx-4 mt-4 xl:mx-auto">
                    <div className="grid grid-cols-1 2xl:grid-cols-3 xl:grid-cols-3 md:grid-cols-2 gap-4">
                        {
                            data.map((section: Section, idx: number) => {
                                return <Cards data={section} key={idx} />;
                            })
                        }
                    </div>
                </section>
                <Footer />
            </main>
        </>
    );
}
