import Navbar from "@/components/Navbar";
import React from "react";
import Footer from "@/components/Footer";
import Head from "next/head";
import { getSections, getSubsectionPost, getSubSections } from "lib/sections";
import { BreadCrumbs } from "@/components/BreadCrumbs";
import { TocLink } from "@/components/Toc";

export async function getStaticPaths() {
    const sections = await getSections()
    const allPaths: any = []
    sections.forEach(async section => {
        const subSections = await getSubSections(section)
        subSections?.forEach(subsection => {
            allPaths.push({ params: { section, subsection } })
        })
    })
    return {
        paths: allPaths,
        fallback: false
    }
}

export async function getStaticProps({ params }: any) {
    const content = await getSubsectionPost(params.section, params.subsection)

    return {
        props: {
            ...content
        }
    }
}

const Subsection = ({ title, content, toc }: any) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                <section className="mt-[100px] m-auto flex justify-center">
                    <div>
                    <BreadCrumbs />
                    <article className='prose dark:prose-invert max-w-[65ch]' dangerouslySetInnerHTML={{ __html: content }}>
                    </article>
                    </div>
                    <nav>
                        {toc != undefined ? <label className="font-bold" htmlFor="toc">Table of content</label>: ''}
                        <TocLink dic={toc}/>
                    </nav>
                </section>
            </main>
            <Footer />
        </>
    )
}

export default Subsection;
