import Navbar from "@/components/Navbar";
import React, { useState } from "react";
import {Footer} from "@/components/Footer";
import Head from "next/head";
import { getSections, getSubsectionPost, getSubSections } from "lib/sections";
import { BreadCrumbs } from "@/components/BreadCrumbs";
import { MDXRemote } from "next-mdx-remote";
import { TableOfContents } from "@/components/Tableofcontent";
import { ActionIcon, Drawer } from "@mantine/core";
import { FiMenu } from "react-icons/fi";

export async function getStaticPaths() {
    const sections = await getSections()
    const allPaths: any = []
    sections.forEach(async section => {
        const subSections = await getSubSections(section)
        subSections?.forEach(subsection => {
            allPaths.push({ params: { section, subsection } })
        })
    })
    return {
        paths: allPaths,
        fallback: false
    }
}

export async function getStaticProps({ params }: any) {
    const content = await getSubsectionPost(params.section, params.subsection)
    const subsection = await getSubSections(params.section)

    return {
        props: {
            source: content,
            section: params.section,
            subsection
        }
    }
}

const Subsection = ({ source, section, subsection }: any) => {
    const [opened, setOpened] = useState(true);
    return (
        <>
            <Head>
                <title>{source.frontmatter.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="w-full flex">
                <TableOfContents links={subsection} section={section} hidden={true}/>
                <Drawer opened={opened} onClose={() => setOpened(false)} className="p-0" withCloseButton={false}>
                    <TableOfContents links={subsection} section={section} hidden={false}/>
                </Drawer>
                <main className="flex-grow flex">
                    <div className="flex-grow sm:w-auto relative justify-between xl:px-4">
                        <nav className="xl:hidden sticky top-0 px-4 min-h-[60px] border-b border-gray-200 dark:border-gray-500 flex justify-between items-center bg-white dark:bg-gray-900 z-10">
                            <ActionIcon onClick={() => setOpened(true)}><FiMenu size={24}/></ActionIcon>
                        </nav>
                        <div className="h-8"/>
                        <article className="xl:w-[80ch] m-auto prose lg:prose-xl dark:prose-invert text-justify px-4">
                            <h2 className="capitalize">{source.frontmatter.title}</h2>
                            {source && <MDXRemote {...source} />}
                        </article>
                        <div className="h-8"/>
                    </div>
                    <div className="xl:min-w-[250px]" />
                </main>
            </div>
        </>
    )
}

export default Subsection;
