import Navbar from "@/components/Navbar";
import React, { useEffect, useState } from "react";
import { Footer } from "@/components/Footer";
import Head from "next/head";
import hljs from "highlight.js";
import "highlight.js/styles/github-dark.css";
import { getSectionIndex, getSections, getSubSections } from "lib/sections";
import { BreadCrumbs } from "@/components/BreadCrumbs";
import { MDXRemote } from "next-mdx-remote";
import { TableOfContents } from "@/components/Tableofcontent";

export async function getStaticPaths() {
    const sections = await getSections();
    const paths = sections.map((section) => ({
        params: { section },
    }));
    return { paths, fallback: false };
}

export async function getStaticProps({ params }: any) {
    const mdxContent = await getSectionIndex(params.section);
    const subsection = await getSubSections(params.section);
    return {
        props: { source: mdxContent, subsection, section: params.section },
    };
}

const Section = ({ source, subsection, section }: any) => {

    useEffect(() => {
        hljs.highlightAll();
    }, []);

    return (
        <>
            <Head>
                <title>{source.frontmatter.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="w-full flex">
                <TableOfContents links={subsection} section={section}/>
                <main className="flex-grow flex">
                    <div className="flex-grow sm:w-auto relative justify-between px-4">
                        <div className="h-8"/>
                        <article className="xl:w-[80ch] m-auto prose lg:prose-xl dark:prose-invert text-justify">
                            <h2 className="capitalize">{source.frontmatter.title}</h2>
                            {source && <MDXRemote {...source} />}
                        </article>
                        <div className="h-8"/>
                    </div>
                    <div className="xl:min-w-[250px]" />
                </main>
            </div>
        </>
    );
};

export default Section;
