import Navbar from '@/components/Navbar'
import React from 'react'
import Footer from '@/components/Footer'
import Head from 'next/head'
import { getSectionIndex, getSections } from 'lib/sections'

export async function getStaticPaths() {
    const sections = getSections();
    const paths = sections.map(section => ({
        params: { section }
    }))
    return { paths, fallback: false }
}

export async function getStaticProps({ params }: any) {
    const index = await getSectionIndex(params.section)
    return {
        props: { ...index }
    }
}

const Section = ({ title, content }: any) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                <section className={"max-w-[70ch] m-auto mt-[100px]"}>
                    <article className='prose dark:prose-invert' dangerouslySetInnerHTML={{__html: content}}>
                    </article>
                </section>
            </main>
            <Footer />
        </>
    )
}

export default Section
