import Navbar from "@/components/Navbar";
import React, { useEffect } from "react";
import Footer from "@/components/Footer";
import { getQuestionById, getQuestions } from "lib/question";
import Head from "next/head";
import hljs from 'highlight.js'
import 'highlight.js/styles/github-dark.css'
import { TocLink } from "@/components/Toc";

export async function getStaticPaths() {
    const questions = await getQuestions();
    const paths = questions.map(question => ({
        params: { question: question.id }
    }))
    return { paths, fallback: false }
}

export async function getStaticProps({ params }: any) {
    const questionData = await getQuestionById(params.question);
    return {
        props: {
            ...questionData
        },
    };
}
const Question = ({ title, date, content, toc }: any) => {
    useEffect(() => {
        hljs.highlightAll()
    }, [])
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <Navbar mode="sticky"/>
                <section className="flex justify-center gap-2">
                    <div>
                        <div className="text-gray-400 text-sm py-2">
                            {`Last updated on ${date}`}
                        </div>
                        <article className="prose lg:prose-xl dark:prose-invert w-[80%]" dangerouslySetInnerHTML={{ __html: content }}>
                        </article>
                    </div>
                    <nav className="sticky h-[539px]">
                        {toc != undefined ? <label className="font-bold" htmlFor="toc">Table of content</label>: ''}
                        <TocLink dic={toc} />
                    </nav>
                </section>
                <Footer />
            </main>
        </>
    );
};

export default Question;
