import Navbar from "@/components/Navbar";
import React from "react";
import Footer from "@/components/Footer";
import { getQuestionById, getQuestions } from "lib/question";
import Head from "next/head";
import { Switch } from "@headlessui/react";

export async function getStaticPaths() {
    const questions = getQuestions();
    const paths = questions.map(post => ({
        params: { question: post.id }
    }))
    return { paths, fallback: false }
}

export async function getStaticProps({ params }: any) {
    const questionData = await getQuestionById(params.question);
    return {
        props: {
            ...questionData
        },
    };
}
const Question = ({ title, date, content }: any) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
               
                <Navbar />
                <section className={"max-w-[70ch] m-auto mt-[100px]"}>
                    
                    <article className="prose dark:prose-invert" dangerouslySetInnerHTML={{ __html: content }}>
                    </article>
                </section>
                <Footer />
            </main>
        </>
    );
};

export default Question;
